import { PolicyPlaybook } from "../ast";

export const ServicesAgreementPlaybook: PolicyPlaybook = {
  id: "playbook-services-standard",
  name: "Master Services Agreement Review",
  version: "1.0.0",
  documentType: "services",
  description: "Enterprise review policy for commercial master services agreements and vendor contracts.",
  rules: [
    {
      id: "RULE_MSA_LIABILITY_CAP_EXCEEDED",
      version: "1.0.0",
      name: "Aggregate Liability Cap Threshold",
      category: "liability",
      severity: "high",
      description: "Aggregate liability must not exceed $1,000,000 or 12 months fees.",
      condition: {
        type: "numeric_threshold",
        field: "liability_cap_usd",
        operator: "<=",
        threshold: 1000000,
        unit: "usd",
      },
      explanationTemplate: "Aggregate liability cap of ${{extractedValue}} exceeds standard commercial policy threshold ($1,000,000).",
      suggestedAction: "Negotiate liability cap down to the total fees paid under the agreement in the prior 12 months.",
    },
    {
      id: "RULE_MSA_LIABILITY_CARVEOUTS",
      version: "1.0.0",
      name: "Standard Exceptions to Liability Cap",
      category: "liability",
      severity: "critical",
      description: "Limitation of liability must carve out gross negligence and willful misconduct.",
      condition: {
        type: "required_exception",
        scopeCategory: "liability",
        requiredExceptions: [
          "gross negligence",
          "willful misconduct",
        ],
      },
      explanationTemplate: "Liability limitation clause completely eliminates liability without standard exceptions: {{missingExceptions}}.",
      suggestedAction: "Add carveouts stating limitations do not apply to gross negligence, willful misconduct, or breach of confidentiality.",
      patchTemplate: {
        replacementText: "The limitations in this Section shall not apply to damages arising from a party's gross negligence, willful misconduct, or breach of Section 7 (Confidentiality).",
        explanation: "Carve out gross negligence and willful misconduct from liability cap.",
      },
    },
    {
      id: "RULE_MSA_PAYMENT_NET_DAYS",
      version: "1.0.0",
      name: "Payment Due Date Terms",
      category: "payment",
      severity: "medium",
      description: "Invoices must not require payment in fewer than 30 days (standard Net 30 or Net 45).",
      condition: {
        type: "numeric_threshold",
        field: "payment_net_days",
        operator: ">=",
        threshold: 30,
        unit: "days",
      },
      explanationTemplate: "Payment window of {{extractedValue}} days is shorter than standard Net 30 terms.",
      suggestedAction: "Change payment terms from Net {{extractedValue}} to Net 30 or Net 45.",
    },
    {
      id: "RULE_MSA_AUTO_RENEWAL_WINDOW",
      version: "1.0.0",
      name: "Auto-Renewal Notice Window Limits",
      category: "termination",
      severity: "high",
      description: "Automatic renewal notice windows should not exceed 60 days.",
      condition: {
        type: "numeric_threshold",
        field: "renewal_notice_window_days",
        operator: "<=",
        threshold: 60,
        unit: "days",
      },
      explanationTemplate: "Automatic renewal requires {{extractedValue}} days advance notice to cancel, exceeding the 60-day limit.",
      suggestedAction: "Reduce non-renewal notice period to 30 days prior to term expiration.",
    },
    {
      id: "RULE_MSA_CROSS_REFERENCE_INTEGRITY",
      version: "1.0.0",
      name: "Cross-Reference Section Integrity",
      category: "drafting",
      severity: "medium",
      description: "All referenced sections must correspond to actual numbered sections in the contract.",
      condition: {
        type: "broken_cross_reference",
      },
      explanationTemplate: "Contract refers to {{brokenReference}} which does not exist in the document.",
      suggestedAction: "Correct the section number reference to point to the valid clause or re-insert the omitted section.",
    },
  ],
};
